server:
  port: 8083

dubbo:
  application:
    name: api-gateway-test
    version: 1.0.0

  registry:
    address: zookeeper://124.221.25.145:2181
    protocol: zookeeper
    timeout: 30000
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.kevin.gateway.rpc
logging:
  level:
    org.apache.dubbo: DEBUG

#api-gateway-sdk:
#  address: http://localhost:6789
#  system-id: api-gateway-test
#  system-name: 网关SDK测试工程
#  system-registry: zookeeper://124.221.25.145:2181
